### PR TITLE
Add modularity

### PR DESCRIPTION
**Pull request by Moonire**
Addition of the modularity module to compute the quality of the clustering. Giving us the ability to choose the best values for our hyperparametres. Supports both dense and sparse matrices. Implementation in accordance with :
Malliaros, Fragkiskos D., and Michalis Vazirgiannis. "Clustering and community detection in directed networks: A survey." Physics Reports 533.4 (2013): 95-142.

Note that the conversion step is costly and isn't perfect as there is no bijection between adjacency and transition matrices.

### CODE REVIEW

**Comment by Moonire** [comment]
Hi Guy,

I've tackled the issues you pointed out and did some refactoring too so that it would be clearer.
I've to get your feedback as soon as possible!

Thanks

**Comment by GuyAllard** [comment]
That looks good.
All the tests pass!
I was experimenting with it today - it is really useful for determining the best cluster inflation value to use.

I will create a new feature branch which contains your work, and will make some additions to the documentation. Once that Is complete, I will merge into master and create a new release.

Thanks!

**Comment by GuyAllard** [comment]
One addition request:
I would like to add you to the list of authors in __init__.py. To do this, I need your (real) name!

**Comment by Moonire** [comment]
Thank you I'd really appreciate it !
Its : Mounir MALLEK

**Comment by GuyAllard** [comment]
I have updated the README, added you to the author list and added the modularity module to the auto docs.

Can you review the README.md on the Moonire-modularity branch and check that the 'Choosing Hyperparameters' section that I have added makes sense?

Thanks!

**Comment by Moonire** [comment]
It makes perfect sense, the exemple is very clear. Maybe mentioning it the features part would be relevant too.

Apart from that, I also think it's ready to merge into master.

**Comment by Moonire** [comment]
Just a question which is probably stupid. What is the usual thing to do with the repo I forked after it's merged ? Should I delete it ?

**Comment by GuyAllard** [comment]
You can delete it.

**Comment by GuyAllard** [comment]
I'm merging this branch into master, everything seems good.
Thanks for your contribution!

**Comment by GuyAllard** [comment]
The updated package is now available on pypi for installation using pip.
https://pypi.org/project/markov-clustering/

**Pull request merged**
